package com.jahndigital.expressive.syntax;

import java.util.ArrayList;

/**
 * Reads the provided text string and converts it into tokens.
 */
final class Lexer {
    private final ArrayList<String> _errors = new ArrayList<>();
    private final String _text;
    private int _position = 0;

    /**
     * Get a list of errors generated by the lexer during processing.
     */
    public Iterable<String> getErrors() {
        return _errors;
    }

    /**
     * Gets the character at the current position, or a null terminator if we've reached the end.
     */
    private char getCurrent() {
        if (_position >= _text.length()) {
            return '\0';
        }

        return _text.charAt(_position);
    }

    /**
     * Init
     *
     * @param text The expression to lex.
     */
    public Lexer(String text) {
        _text = text;
    }

    /**
     * Increments the position forward by one.
     */
    private void next() {
        _position++;
    }

    /**
     * Get the next token from the text and return it as a SyntaxToken object.
     *
     * @return The next token in the text, or an EndOfFileToken.
     */
    public SyntaxToken NextToken() {
        if (_position >= _text.length()) {
            return new SyntaxToken(SyntaxKind.EndOfFileToken, _position, "\0", null);
        }

        if (Character.isDigit(getCurrent())) {
            int start = _position;

            while (Character.isDigit(getCurrent())) {
                next();
            }

            String text = _text.substring(start, _position);

            Integer num = null;
            try {
                num = Integer.parseInt(text);
            } catch (NumberFormatException e) {
                _errors.add(String.format("ERROR: The number '%s' is not a valid Int32", _text));
            }

            return new SyntaxToken(SyntaxKind.NumberToken, start, text, num);
        }

        if (Character.isWhitespace(getCurrent())) {
            int start = _position;

            while (Character.isWhitespace(getCurrent())) {
                next();
            }

            String text = _text.substring(start, _position);
            return new SyntaxToken(SyntaxKind.WhitespaceToken, start, text, null);
        }

        if (Character.isLetter(getCurrent())) {
            int start = _position;

            while (Character.isLetter(getCurrent()) || Character.isDigit(getCurrent())) {
                next();
            }

            String text = _text.substring(start, _position);
            SyntaxKind kind = SyntaxFacts.getKeywordKind(text);
            return new SyntaxToken(kind, start, text, null);
        }

        switch (getCurrent()) {
            case '+':
                return new SyntaxToken(SyntaxKind.PlusToken, _position++, "+", null);
            case '-':
                return new SyntaxToken(SyntaxKind.MinusToken, _position++, "-", null);
            case '*':
                return new SyntaxToken(SyntaxKind.StarToken, _position++, "*", null);
            case '/':
                return new SyntaxToken(SyntaxKind.SlashToken, _position++, "/", null);
            case '(':
                return new SyntaxToken(SyntaxKind.OpenParenthesisToken, _position++, "(", null);
            case ')':
                return new SyntaxToken(SyntaxKind.CloseParenthesisToken, _position++, ")", null);
        }

        _errors.add(String.format("ERROR: Bad character input '%s' at position %d.", getCurrent(), _position));
        return new SyntaxToken(SyntaxKind.BadToken, _position++, _text.substring(_position - 1, _position), null);
    }
}
